name: Redwood Deploy

on:
  push:
    branches:
      - main    # Adjust this if your branch is different
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Redwood binary
        run: go build -o redwood .

      - name: Set up WireGuard connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      - name: Install SSH tools
        run: sudo apt-get update && sudo apt-get install -y openssh-client sshpass rsync

      - name: Ensure target directories exist and back up old version
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no support@10.100.90.77 \
            "echo '${{ secrets.SSH_PASSWORD }}' | sudo -S bash -c 'mkdir -p /var/www/redwood /var/www/redwood.bak && rsync -avz --delete /var/www/redwood/ /var/www/redwood.bak/'"

      - name: Upload Redwood binary to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            --rsync-path="echo '${{ secrets.SSH_PASSWORD }}' | sudo -S rsync" \
            ./redwood support@10.100.90.77:/var/www/redwood/

      - name: Restart Redwood service on server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no support@10.100.90.77 \
            "echo '${{ secrets.SSH_PASSWORD }}' | sudo -S systemctl restart redwood.service"
